language: java
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 3f9735fe52773d87a6044fed49dd802718f88e49
  keep_history: true
  on:
    branch: master
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw